#!/usr/bin/sh


echo press 1 to mount 2 to unmount
read y;

if [ $y -eq 1 ]
then
echo give the mnt number
read x;
mkdir -p disks/
p=$(lsblk /dev/sda"$x" -f | tail -1 | cut -d' ' -f11)
mkdir disks/$p
sudo mount /dev/sda"$x"  /home/"$(whoami)"/disks/"$p"
rmdir  --ignore-fail-on-non-empty /home/"$(whoami)"/disks/"$p"
rmdir  --ignore-fail-on-non-empty /home/"$(whoami)"/disks/

#disksctl mount -b /dev/sda$x
#ranger /run/media/"$(whoami)"/
ranger /home/"$(whoami)"/disks/
fi

if [ $y -eq 2 ]
then 
echo give the mnt number
read z;

#disksctl unmount -b /dev/sda$z;
p=$(lsblk /dev/sda"$z" -f | tail -1 | cut -d' ' -f11)
sudo umount   /home/"$(whoami)"/disks/"$p"
rmdir  --ignore-fail-on-non-empty /home/"$(whoami)"/disks/"$p"
rmdir  --ignore-fail-on-non-empty /home/"$(whoami)"/disks/ 
fi
