#!/usr/bin/sh


echo press 1 to mount 2 to unmount
read y;

if [ $y -eq 1 ]
then
echo give the mnt number
read x;


p=$(lsblk  -o label /dev/sdb"$x" | tail -1)
mkdir -p disks/
mkdir -p  disks/"$p"
#sudo mkdir /mnt/"$p"
sudo mount   /dev/sdb"$x" /home/$(whoami)/disks/"$p" -o uid=jerome
sudo rmdir --ignore-fail-on-non-empty /home/$(whoami)/disks"$p"
rmdir --ignore-fail-on-non-empty /home/jerome/disks
#disksctl mount -b /dev/sdb$x
#ranger /run/media/"$(whoami)"/ &
ranger /home/$(whoami)/disks/"$p"
fi

if [ $y -eq 2 ]
then 
echo give the mnt number
read z;

#mount all
if [ $z = a ]
then
sudo umount -a	
rmdir --ignore-fail-on-non-empty /home/$(whoami)/disks/*
rmdir --ignore-fail-on-non-empty /home/$(whoami)/disks


else
p=$(lsblk  -o label /dev/sdb"$z" | tail -1)
sudo umount   /home/$(whoami)/disks/"$p"

#disksctl unmount -b /dev/sdb$z;
sudo rmdir --ignore-fail-on-non-empty /home/$(whoami)/disks/"$p"
#rmdir --ignore-fail-on-non-empty /home/$(whoami)/disks/
fi
fi


