#!/bin/sh
# PekWM start file
# This file is a simple shell script; It gets run on pekwm startup, after 
# the theme and all config has loaded if it is set executable
# (chmod +x start).
#
# This is different from ~/.xinitrc because a normal configuration of 
# .xinitrc you'll run all commands, then launch the window manager last.
#
# It also gets re-run every time pekwm is restarted.
# 
# As for it's usefulness, well, it's up to you. I actually set my background
# from my start file; since it runs after the theme gets loaded, this 
# effectively overrides whatever's in the theme.
# 
# There's probably a few other good uses for it, too. I mainly pushed for it
# because when I was doing fluxbox's docs, people used to complain that there
# wasn't one, and I wanted to avoid that for pekwm. ;) --eyez
xrandr --output eDP1 --mode 1920x1080 --rate 59.74 &
# Set background image
nitrogen --restore &


killall pulseaudio &
killall tint2 &
redshift -x
killall volumeicon &
killall nm-applet  &
killall /usr/lib/systemd/systemd &
killall sxhkd


sxhkd & 

redshift -O 4000

pulseaudio &
killall /usr/lib/pulse/gsettings-helper
#sh volumeicon &
nm-applet &
