#! /bin/sh
#xrandr --output eDP1 --mode 1280x720 --rate 59.74 &
#xrandr --output eDP1 --mode 2048x1152 --rate 59.91 &
xrandr --output eDP1 --mode 1920x1080 --rate 59.74 &
# Set background image
nitrogen --restore &

killall tint2 &
redshift -x
killall volumeicon &
killall nm-applet  &
killall /usr/lib/systemd/systemd &
killall sxhkd
sxhkd &

numlockx &
xset b off

xbacklight -set 6% &
#amixer -q sset 'Master' 20% &
pactl set-sink-volume 0 15% &

redshift -O 4000
tint2 &

pulseaudio &
killall /usr/lib/pulse/gsettings-helper
#sh volumeicon &
nm-applet &
bspc monitor -d 1 2 3 4 
#5 6 7 8 9 10
#I II III IV V VI VII VIII IX X

bspc config border_width         3
#bspc config window_gap      0
#bspc config window_gap          5
#bspc config window_gap      10
#bspc config window_gap		16
bspc config window_gap      20
#bspc config window_gap       25
#bspc config window_gap       45
#bspc config window_gap       75
#bspc config window_gap       90


#bspwm split system

#bspc config automatic_scheme	longest_side
bspc config automatic_scheme	spiral
#bspc config automatic_scheme	alternate

#On which child should a new window be attached when adding a window
#bspc config initial_polarity "first_child"
bspc config initial_polarity "second_child"


bspc config split_ratio		0.5
#bspc config split_ratio          0.52

bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc node -t pseudo_tiled
#extras
bspc config border_width        1
bspc config focus_follows_pointer true

#bspc config top_padding		0
bspc config bottom_padding	-4


#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a palemoon desktop='^2'
bspc rule -a Surf  -t state=tiled
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

#nitrogen --restore
#feh --bg-scale /home/eel52/Pictures/wallpaper.jpg

#bspc monitor HDMI-1 -d ä¸€ äºŒ ä¸‰ å›› äº”
#bspc monitor DP-1 -d å…­ ä¸ƒ å…« ä¹ å
#bspc monitor HDMI-0 -d åä¸€ åäºŒ

#bspc monitor HDMI-1 -n center
#bspc monitor HDMI-0 -n above
#bspc monitor DP-1 -n right


# source the colors.
#. "/home/eel52/.cache/wal/colors.sh"

# Set the border colors.
#bspc config normal_border_color "$color2"
bspc config normal_border_color "#575863"
#bspc config active_border_color "$color2"
bspc config active_border_color "#575863"
#bspc config focused_border_color "$color15"
bspc config focused_border_color "#DADCDE"
#bspc config presel_border_color "#575863"
bspc config presel_feedback_color "#575863"
#bspc config urgent_border_color "$color2"

#bspc rule -a Galculator floating=on state=floating
#bspc rule -a Yad floating=on state=floating
#bspc rule -a Soffice floating=off state=tiled
#bspc rule -a Pavucontrol floating=on state=floating
#bspc rule -a Xsensors floating=on state=floating
#bspc rule -a xterm floating=on state=floating
#bspc rule -a XTerm floating=on state=floating
bspc rule -a URxvt:cmus pseudo_tiled=on state=pseudo_tiled
bspc rule -a URxvt:sysinfo floating=on state=floating
#bspc rule -a URxvt:updates floating=on state=floating

# Startup Applications Config

#bspc rule -a URxvt:urxvt -o node=@^1:^2:/
#bspc rule -a Steam:Steam node=@^1:^5:/1
#bspc rule -a Surf:Surf node=@^3:^4:/
#bspc rule -a URxvt:cmus node=@^1:^4:/
#bspc rule -a URxvt:weechat node=@^1:^2:/
#bspc rule -a discord:discord node=@^1:^3:/
#bspc rule -a Thunderbird:Mail node=@^1:^4:/
#bspc rule -a URxvt:neomutt node=@^1:^4:/
#bspc rule -a riot:riot node=@^1:^3:/

#bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
#~/.config/polybar/launch.sh
#sleep 2
bspc config top_padding 0
# Startup Applications
#exec /home/eel52/scripts/startup_applications.sh
#exec thunderbird &
#exec discord-canary &
#exec steam-native &
#exec sleep 3 && urxvt -name "weechat" -e "weechat" &
#exec sleep 3 && urxvt -name "cmus" -e "cmus" &

#xinput disable 11

#xrdb ~/.Xdefaults

#surffie
#bspc rule --add beta:alpha state=tiled
bspc rule --add Surf:surf state=tiled
bspc rule -a Surf state=tiled
bspc rule -a surf state=tiled
bspc rule -a Surf state=tile
bspc rule -a surf state=tile
